dist: trusty
sudo: false
language: cpp
script:
 - mkdir build && cd build
 - cmake -D ENABLE_COVERAGE:BOOL=TRUE ..
 - make
 - ./knockoutTest
 - ./knockoutApp

after_success: 
 - bash <(curl -s https://codecov.io/bash)
